version: 2
updates:
  # Monitoramento de segurança e atualizações do Backend Node.js
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "security"
      - "dependencies"
      - "backend"

  # Monitoramento de segurança e atualizações do Frontend React
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "security"
      - "dependencies"
      - "frontend"

  # Monitoramento de segurança e atualizações do Backend Python
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "security"
      - "dependencies"
      - "python"
